excluded:
    - Carthage
    - Tunnel
disabled_rules:
 - line_length
 - trailing_whitespace
 - todo
 - cyclomatic_complexity
 - file_length
 - type_body_length
 - function_body_length
 - nesting
opt_in_rules:
 - empty_count
 - empty_string
 - implicitly_unwrapped_optional
 - legacy_random
 - let_var_whitespace
 - literal_expression_end_indentation
 - override_in_extension
 - redundant_type_annotation
 - toggle_bool
 - unneeded_parentheses_in_closure_argument
 - unused_import
 - trailing_closure
identifier_name:
  min_length:
    warning: 0
